package com.ds.money.entity;

public class DsFromKeyType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_from_key_type.id
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_from_key_type.type_name
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_from_key_type.fk_from_key
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	private String fkFromKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_from_key_type.game_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	private String gameType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_from_key_type.state
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_from_key_type.id
	 * @return  the value of ds_from_key_type.id
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_from_key_type.id
	 * @param id  the value for ds_from_key_type.id
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_from_key_type.type_name
	 * @return  the value of ds_from_key_type.type_name
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_from_key_type.type_name
	 * @param typeName  the value for ds_from_key_type.type_name
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName == null ? null : typeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_from_key_type.fk_from_key
	 * @return  the value of ds_from_key_type.fk_from_key
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public String getFkFromKey() {
		return fkFromKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_from_key_type.fk_from_key
	 * @param fkFromKey  the value for ds_from_key_type.fk_from_key
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public void setFkFromKey(String fkFromKey) {
		this.fkFromKey = fkFromKey == null ? null : fkFromKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_from_key_type.game_type
	 * @return  the value of ds_from_key_type.game_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public String getGameType() {
		return gameType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_from_key_type.game_type
	 * @param gameType  the value for ds_from_key_type.game_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public void setGameType(String gameType) {
		this.gameType = gameType == null ? null : gameType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_from_key_type.state
	 * @return  the value of ds_from_key_type.state
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_from_key_type.state
	 * @param state  the value for ds_from_key_type.state
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}