package com.ds.money.entity;

public class DSGameInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_game_info.id
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_game_info.fk_from_key_id
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    private Integer fkFromKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_game_info.game_type
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    private String gameType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_game_info.game_name
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    private String gameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_game_info.state
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_game_info.memo
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_game_info.id
     *
     * @return the value of ds_game_info.id
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_game_info.id
     *
     * @param id the value for ds_game_info.id
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_game_info.fk_from_key_id
     *
     * @return the value of ds_game_info.fk_from_key_id
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public Integer getFkFromKeyId() {
        return fkFromKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_game_info.fk_from_key_id
     *
     * @param fkFromKeyId the value for ds_game_info.fk_from_key_id
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public void setFkFromKeyId(Integer fkFromKeyId) {
        this.fkFromKeyId = fkFromKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_game_info.game_type
     *
     * @return the value of ds_game_info.game_type
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public String getGameType() {
        return gameType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_game_info.game_type
     *
     * @param gameType the value for ds_game_info.game_type
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public void setGameType(String gameType) {
        this.gameType = gameType == null ? null : gameType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_game_info.game_name
     *
     * @return the value of ds_game_info.game_name
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_game_info.game_name
     *
     * @param gameName the value for ds_game_info.game_name
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_game_info.state
     *
     * @return the value of ds_game_info.state
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_game_info.state
     *
     * @param state the value for ds_game_info.state
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_game_info.memo
     *
     * @return the value of ds_game_info.memo
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_game_info.memo
     *
     * @param memo the value for ds_game_info.memo
     *
     * @mbggenerated Fri Oct 30 16:29:30 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}