package com.ds.money.entity;

public class DSIPList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_ip_list.id
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_ip_list.ip
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_ip_list.name
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_ip_list.state
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_ip_list.memo
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_ip_list.id
     *
     * @return the value of ds_ip_list.id
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_ip_list.id
     *
     * @param id the value for ds_ip_list.id
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_ip_list.ip
     *
     * @return the value of ds_ip_list.ip
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_ip_list.ip
     *
     * @param ip the value for ds_ip_list.ip
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_ip_list.name
     *
     * @return the value of ds_ip_list.name
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_ip_list.name
     *
     * @param name the value for ds_ip_list.name
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_ip_list.state
     *
     * @return the value of ds_ip_list.state
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_ip_list.state
     *
     * @param state the value for ds_ip_list.state
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_ip_list.memo
     *
     * @return the value of ds_ip_list.memo
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_ip_list.memo
     *
     * @param memo the value for ds_ip_list.memo
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}