package com.ds.money.entity;

import java.math.BigDecimal;

public class DsMemberMoney {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.id
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.site_id
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.username
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.money
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private BigDecimal money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.password
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.state
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money.version
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.id
	 * @return  the value of ds_member_money.id
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.id
	 * @param id  the value for ds_member_money.id
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.site_id
	 * @return  the value of ds_member_money.site_id
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.site_id
	 * @param siteId  the value for ds_member_money.site_id
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.username
	 * @return  the value of ds_member_money.username
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.username
	 * @param username  the value for ds_member_money.username
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.money
	 * @return  the value of ds_member_money.money
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public BigDecimal getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.money
	 * @param money  the value for ds_member_money.money
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.password
	 * @return  the value of ds_member_money.password
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.password
	 * @param password  the value for ds_member_money.password
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.state
	 * @return  the value of ds_member_money.state
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.state
	 * @param state  the value for ds_member_money.state
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money.version
	 * @return  the value of ds_member_money.version
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money.version
	 * @param version  the value for ds_member_money.version
	 * @mbggenerated  Wed Aug 12 03:06:15 EDT 2015
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}