package com.ds.money.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DsMemberMoneyLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.username
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.hashcode
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String hashcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.site_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.sitename
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String sitename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.from_key
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String fromKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.request_ip
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String requestIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.trans_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String transId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.from_key_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private Integer fromKeyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.before_money
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private BigDecimal beforeMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.remit
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private BigDecimal remit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.after_money
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private BigDecimal afterMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.trans_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String transType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.game_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String gameType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.game_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String gameId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.create_time
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_member_money_log.memo
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	private String memo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.id
	 * @return  the value of ds_member_money_log.id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.id
	 * @param id  the value for ds_member_money_log.id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.username
	 * @return  the value of ds_member_money_log.username
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.username
	 * @param username  the value for ds_member_money_log.username
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.hashcode
	 * @return  the value of ds_member_money_log.hashcode
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getHashcode() {
		return hashcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.hashcode
	 * @param hashcode  the value for ds_member_money_log.hashcode
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setHashcode(String hashcode) {
		this.hashcode = hashcode == null ? null : hashcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.site_id
	 * @return  the value of ds_member_money_log.site_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.site_id
	 * @param siteId  the value for ds_member_money_log.site_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.sitename
	 * @return  the value of ds_member_money_log.sitename
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getSitename() {
		return sitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.sitename
	 * @param sitename  the value for ds_member_money_log.sitename
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setSitename(String sitename) {
		this.sitename = sitename == null ? null : sitename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.from_key
	 * @return  the value of ds_member_money_log.from_key
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getFromKey() {
		return fromKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.from_key
	 * @param fromKey  the value for ds_member_money_log.from_key
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setFromKey(String fromKey) {
		this.fromKey = fromKey == null ? null : fromKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.request_ip
	 * @return  the value of ds_member_money_log.request_ip
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getRequestIp() {
		return requestIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.request_ip
	 * @param requestIp  the value for ds_member_money_log.request_ip
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp == null ? null : requestIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.trans_id
	 * @return  the value of ds_member_money_log.trans_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getTransId() {
		return transId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.trans_id
	 * @param transId  the value for ds_member_money_log.trans_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setTransId(String transId) {
		this.transId = transId == null ? null : transId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.from_key_type
	 * @return  the value of ds_member_money_log.from_key_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public Integer getFromKeyType() {
		return fromKeyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.from_key_type
	 * @param fromKeyType  the value for ds_member_money_log.from_key_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setFromKeyType(Integer fromKeyType) {
		this.fromKeyType = fromKeyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.before_money
	 * @return  the value of ds_member_money_log.before_money
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public BigDecimal getBeforeMoney() {
		return beforeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.before_money
	 * @param beforeMoney  the value for ds_member_money_log.before_money
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setBeforeMoney(BigDecimal beforeMoney) {
		this.beforeMoney = beforeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.remit
	 * @return  the value of ds_member_money_log.remit
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public BigDecimal getRemit() {
		return remit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.remit
	 * @param remit  the value for ds_member_money_log.remit
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setRemit(BigDecimal remit) {
		this.remit = remit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.after_money
	 * @return  the value of ds_member_money_log.after_money
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public BigDecimal getAfterMoney() {
		return afterMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.after_money
	 * @param afterMoney  the value for ds_member_money_log.after_money
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setAfterMoney(BigDecimal afterMoney) {
		this.afterMoney = afterMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.trans_type
	 * @return  the value of ds_member_money_log.trans_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getTransType() {
		return transType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.trans_type
	 * @param transType  the value for ds_member_money_log.trans_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setTransType(String transType) {
		this.transType = transType == null ? null : transType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.game_type
	 * @return  the value of ds_member_money_log.game_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getGameType() {
		return gameType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.game_type
	 * @param gameType  the value for ds_member_money_log.game_type
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setGameType(String gameType) {
		this.gameType = gameType == null ? null : gameType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.game_id
	 * @return  the value of ds_member_money_log.game_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getGameId() {
		return gameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.game_id
	 * @param gameId  the value for ds_member_money_log.game_id
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setGameId(String gameId) {
		this.gameId = gameId == null ? null : gameId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.create_time
	 * @return  the value of ds_member_money_log.create_time
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.create_time
	 * @param createTime  the value for ds_member_money_log.create_time
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_member_money_log.memo
	 * @return  the value of ds_member_money_log.memo
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_member_money_log.memo
	 * @param memo  the value for ds_member_money_log.memo
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}
}