package com.ds.money.dao.mapper;

import com.ds.money.entity.CheckEntity;
import com.ds.money.entity.CheckEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CheckEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int countByExample(CheckEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int deleteByExample(CheckEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int insert(CheckEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int insertSelective(CheckEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	List<CheckEntity> selectByExample(CheckEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	CheckEntity selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int updateByExampleSelective(@Param("record") CheckEntity record,
                                 @Param("example") CheckEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int updateByExample(@Param("record") CheckEntity record,
                        @Param("example") CheckEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int updateByPrimaryKeySelective(CheckEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_check_id
	 * @mbggenerated  Fri Sep 18 08:58:16 EDT 2015
	 */
	int updateByPrimaryKey(CheckEntity record);
}