package com.ds.money.dao.mapper;

import com.ds.money.entity.DsFromKeyType;
import com.ds.money.entity.DsFromKeyTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DsFromKeyTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int countByExample(DsFromKeyTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int deleteByExample(DsFromKeyTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int insert(DsFromKeyType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int insertSelective(DsFromKeyType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	List<DsFromKeyType> selectByExample(DsFromKeyTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	DsFromKeyType selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DsFromKeyType record,
                                 @Param("example") DsFromKeyTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int updateByExample(@Param("record") DsFromKeyType record,
                        @Param("example") DsFromKeyTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int updateByPrimaryKeySelective(DsFromKeyType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_from_key_type
	 * @mbggenerated  Wed Oct 14 00:55:56 CST 2015
	 */
	int updateByPrimaryKey(DsFromKeyType record);
}