package com.ds.money.dao.mapper;

import com.ds.money.entity.DsMemberMoneyLog;
import com.ds.money.entity.DsMemberMoneyLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DsMemberMoneyLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int countByExample(DsMemberMoneyLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int deleteByExample(DsMemberMoneyLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int insert(DsMemberMoneyLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int insertSelective(DsMemberMoneyLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	List<DsMemberMoneyLog> selectByExample(DsMemberMoneyLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	DsMemberMoneyLog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DsMemberMoneyLog record,
                                 @Param("example") DsMemberMoneyLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int updateByExample(@Param("record") DsMemberMoneyLog record,
                        @Param("example") DsMemberMoneyLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int updateByPrimaryKeySelective(DsMemberMoneyLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	int updateByPrimaryKey(DsMemberMoneyLog record);
}