package com.ds.money.dao.mapper;

import com.ds.money.entity.DsMoneyConfig;
import com.ds.money.entity.DsMoneyConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DsMoneyConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int countByExample(DsMoneyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int deleteByExample(DsMoneyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int insert(DsMoneyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int insertSelective(DsMoneyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	List<DsMoneyConfig> selectByExample(DsMoneyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	DsMoneyConfig selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DsMoneyConfig record,
                                 @Param("example") DsMoneyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int updateByExample(@Param("record") DsMoneyConfig record,
                        @Param("example") DsMoneyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int updateByPrimaryKeySelective(DsMoneyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	int updateByPrimaryKey(DsMoneyConfig record);
}