package com.ds.money.dao.mapper;

import com.ds.money.entity.MemberEntity;
import com.ds.money.entity.MemberEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MemberEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int countByExample(MemberEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int deleteByExample(MemberEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int insert(MemberEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int insertSelective(MemberEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    List<MemberEntity> selectByExample(MemberEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    MemberEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int updateByExampleSelective(@Param("record") MemberEntity record, @Param("example") MemberEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int updateByExample(@Param("record") MemberEntity record, @Param("example") MemberEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int updateByPrimaryKeySelective(MemberEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    int updateByPrimaryKey(MemberEntity record);
}