package com.ds.money.dao.mapper;

import com.ds.money.entity.DSIPList;
import com.ds.money.entity.DSIPListExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DSIPListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int countByExample(DSIPListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int deleteByExample(DSIPListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int insert(DSIPList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int insertSelective(DSIPList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    List<DSIPList> selectByExample(DSIPListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    DSIPList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int updateByExampleSelective(@Param("record") DSIPList record, @Param("example") DSIPListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int updateByExample(@Param("record") DSIPList record, @Param("example") DSIPListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int updateByPrimaryKeySelective(DSIPList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ip_list
     *
     * @mbggenerated Sat Oct 10 14:58:16 CST 2015
     */
    int updateByPrimaryKey(DSIPList record);
}