package com.ds.money.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DsMemberMoneyLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public DsMemberMoneyLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andHashcodeIsNull() {
			addCriterion("hashcode is null");
			return (Criteria) this;
		}

		public Criteria andHashcodeIsNotNull() {
			addCriterion("hashcode is not null");
			return (Criteria) this;
		}

		public Criteria andHashcodeEqualTo(String value) {
			addCriterion("hashcode =", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotEqualTo(String value) {
			addCriterion("hashcode <>", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeGreaterThan(String value) {
			addCriterion("hashcode >", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeGreaterThanOrEqualTo(String value) {
			addCriterion("hashcode >=", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeLessThan(String value) {
			addCriterion("hashcode <", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeLessThanOrEqualTo(String value) {
			addCriterion("hashcode <=", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeLike(String value) {
			addCriterion("hashcode like", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotLike(String value) {
			addCriterion("hashcode not like", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeIn(List<String> values) {
			addCriterion("hashcode in", values, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotIn(List<String> values) {
			addCriterion("hashcode not in", values, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeBetween(String value1, String value2) {
			addCriterion("hashcode between", value1, value2, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotBetween(String value1, String value2) {
			addCriterion("hashcode not between", value1, value2, "hashcode");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNull() {
			addCriterion("site_id is null");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNotNull() {
			addCriterion("site_id is not null");
			return (Criteria) this;
		}

		public Criteria andSiteIdEqualTo(Integer value) {
			addCriterion("site_id =", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotEqualTo(Integer value) {
			addCriterion("site_id <>", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThan(Integer value) {
			addCriterion("site_id >", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("site_id >=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThan(Integer value) {
			addCriterion("site_id <", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThanOrEqualTo(Integer value) {
			addCriterion("site_id <=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdIn(List<Integer> values) {
			addCriterion("site_id in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotIn(List<Integer> values) {
			addCriterion("site_id not in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdBetween(Integer value1, Integer value2) {
			addCriterion("site_id between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotBetween(Integer value1, Integer value2) {
			addCriterion("site_id not between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andSitenameIsNull() {
			addCriterion("sitename is null");
			return (Criteria) this;
		}

		public Criteria andSitenameIsNotNull() {
			addCriterion("sitename is not null");
			return (Criteria) this;
		}

		public Criteria andSitenameEqualTo(String value) {
			addCriterion("sitename =", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameNotEqualTo(String value) {
			addCriterion("sitename <>", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameGreaterThan(String value) {
			addCriterion("sitename >", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameGreaterThanOrEqualTo(String value) {
			addCriterion("sitename >=", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameLessThan(String value) {
			addCriterion("sitename <", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameLessThanOrEqualTo(String value) {
			addCriterion("sitename <=", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameLike(String value) {
			addCriterion("sitename like", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameNotLike(String value) {
			addCriterion("sitename not like", value, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameIn(List<String> values) {
			addCriterion("sitename in", values, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameNotIn(List<String> values) {
			addCriterion("sitename not in", values, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameBetween(String value1, String value2) {
			addCriterion("sitename between", value1, value2, "sitename");
			return (Criteria) this;
		}

		public Criteria andSitenameNotBetween(String value1, String value2) {
			addCriterion("sitename not between", value1, value2, "sitename");
			return (Criteria) this;
		}

		public Criteria andFromKeyIsNull() {
			addCriterion("from_key is null");
			return (Criteria) this;
		}

		public Criteria andFromKeyIsNotNull() {
			addCriterion("from_key is not null");
			return (Criteria) this;
		}

		public Criteria andFromKeyEqualTo(String value) {
			addCriterion("from_key =", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotEqualTo(String value) {
			addCriterion("from_key <>", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyGreaterThan(String value) {
			addCriterion("from_key >", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyGreaterThanOrEqualTo(String value) {
			addCriterion("from_key >=", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyLessThan(String value) {
			addCriterion("from_key <", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyLessThanOrEqualTo(String value) {
			addCriterion("from_key <=", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyLike(String value) {
			addCriterion("from_key like", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotLike(String value) {
			addCriterion("from_key not like", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyIn(List<String> values) {
			addCriterion("from_key in", values, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotIn(List<String> values) {
			addCriterion("from_key not in", values, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyBetween(String value1, String value2) {
			addCriterion("from_key between", value1, value2, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotBetween(String value1, String value2) {
			addCriterion("from_key not between", value1, value2, "fromKey");
			return (Criteria) this;
		}

		public Criteria andRequestIpIsNull() {
			addCriterion("request_ip is null");
			return (Criteria) this;
		}

		public Criteria andRequestIpIsNotNull() {
			addCriterion("request_ip is not null");
			return (Criteria) this;
		}

		public Criteria andRequestIpEqualTo(String value) {
			addCriterion("request_ip =", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpNotEqualTo(String value) {
			addCriterion("request_ip <>", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpGreaterThan(String value) {
			addCriterion("request_ip >", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpGreaterThanOrEqualTo(String value) {
			addCriterion("request_ip >=", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpLessThan(String value) {
			addCriterion("request_ip <", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpLessThanOrEqualTo(String value) {
			addCriterion("request_ip <=", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpLike(String value) {
			addCriterion("request_ip like", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpNotLike(String value) {
			addCriterion("request_ip not like", value, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpIn(List<String> values) {
			addCriterion("request_ip in", values, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpNotIn(List<String> values) {
			addCriterion("request_ip not in", values, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpBetween(String value1, String value2) {
			addCriterion("request_ip between", value1, value2, "requestIp");
			return (Criteria) this;
		}

		public Criteria andRequestIpNotBetween(String value1, String value2) {
			addCriterion("request_ip not between", value1, value2, "requestIp");
			return (Criteria) this;
		}

		public Criteria andTransIdIsNull() {
			addCriterion("trans_id is null");
			return (Criteria) this;
		}

		public Criteria andTransIdIsNotNull() {
			addCriterion("trans_id is not null");
			return (Criteria) this;
		}

		public Criteria andTransIdEqualTo(String value) {
			addCriterion("trans_id =", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdNotEqualTo(String value) {
			addCriterion("trans_id <>", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdGreaterThan(String value) {
			addCriterion("trans_id >", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdGreaterThanOrEqualTo(String value) {
			addCriterion("trans_id >=", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdLessThan(String value) {
			addCriterion("trans_id <", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdLessThanOrEqualTo(String value) {
			addCriterion("trans_id <=", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdLike(String value) {
			addCriterion("trans_id like", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdNotLike(String value) {
			addCriterion("trans_id not like", value, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdIn(List<String> values) {
			addCriterion("trans_id in", values, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdNotIn(List<String> values) {
			addCriterion("trans_id not in", values, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdBetween(String value1, String value2) {
			addCriterion("trans_id between", value1, value2, "transId");
			return (Criteria) this;
		}

		public Criteria andTransIdNotBetween(String value1, String value2) {
			addCriterion("trans_id not between", value1, value2, "transId");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeIsNull() {
			addCriterion("from_key_type is null");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeIsNotNull() {
			addCriterion("from_key_type is not null");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeEqualTo(Integer value) {
			addCriterion("from_key_type =", value, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeNotEqualTo(Integer value) {
			addCriterion("from_key_type <>", value, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeGreaterThan(Integer value) {
			addCriterion("from_key_type >", value, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("from_key_type >=", value, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeLessThan(Integer value) {
			addCriterion("from_key_type <", value, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeLessThanOrEqualTo(Integer value) {
			addCriterion("from_key_type <=", value, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeIn(List<Integer> values) {
			addCriterion("from_key_type in", values, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeNotIn(List<Integer> values) {
			addCriterion("from_key_type not in", values, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeBetween(Integer value1, Integer value2) {
			addCriterion("from_key_type between", value1, value2, "fromKeyType");
			return (Criteria) this;
		}

		public Criteria andFromKeyTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("from_key_type not between", value1, value2,
					"fromKeyType");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyIsNull() {
			addCriterion("before_money is null");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyIsNotNull() {
			addCriterion("before_money is not null");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyEqualTo(BigDecimal value) {
			addCriterion("before_money =", value, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyNotEqualTo(BigDecimal value) {
			addCriterion("before_money <>", value, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyGreaterThan(BigDecimal value) {
			addCriterion("before_money >", value, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("before_money >=", value, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyLessThan(BigDecimal value) {
			addCriterion("before_money <", value, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("before_money <=", value, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyIn(List<BigDecimal> values) {
			addCriterion("before_money in", values, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyNotIn(List<BigDecimal> values) {
			addCriterion("before_money not in", values, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("before_money between", value1, value2, "beforeMoney");
			return (Criteria) this;
		}

		public Criteria andBeforeMoneyNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("before_money not between", value1, value2,
					"beforeMoney");
			return (Criteria) this;
		}

		public Criteria andRemitIsNull() {
			addCriterion("remit is null");
			return (Criteria) this;
		}

		public Criteria andRemitIsNotNull() {
			addCriterion("remit is not null");
			return (Criteria) this;
		}

		public Criteria andRemitEqualTo(BigDecimal value) {
			addCriterion("remit =", value, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitNotEqualTo(BigDecimal value) {
			addCriterion("remit <>", value, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitGreaterThan(BigDecimal value) {
			addCriterion("remit >", value, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("remit >=", value, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitLessThan(BigDecimal value) {
			addCriterion("remit <", value, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitLessThanOrEqualTo(BigDecimal value) {
			addCriterion("remit <=", value, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitIn(List<BigDecimal> values) {
			addCriterion("remit in", values, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitNotIn(List<BigDecimal> values) {
			addCriterion("remit not in", values, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("remit between", value1, value2, "remit");
			return (Criteria) this;
		}

		public Criteria andRemitNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("remit not between", value1, value2, "remit");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyIsNull() {
			addCriterion("after_money is null");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyIsNotNull() {
			addCriterion("after_money is not null");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyEqualTo(BigDecimal value) {
			addCriterion("after_money =", value, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyNotEqualTo(BigDecimal value) {
			addCriterion("after_money <>", value, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyGreaterThan(BigDecimal value) {
			addCriterion("after_money >", value, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("after_money >=", value, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyLessThan(BigDecimal value) {
			addCriterion("after_money <", value, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("after_money <=", value, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyIn(List<BigDecimal> values) {
			addCriterion("after_money in", values, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyNotIn(List<BigDecimal> values) {
			addCriterion("after_money not in", values, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("after_money between", value1, value2, "afterMoney");
			return (Criteria) this;
		}

		public Criteria andAfterMoneyNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("after_money not between", value1, value2,
					"afterMoney");
			return (Criteria) this;
		}

		public Criteria andTransTypeIsNull() {
			addCriterion("trans_type is null");
			return (Criteria) this;
		}

		public Criteria andTransTypeIsNotNull() {
			addCriterion("trans_type is not null");
			return (Criteria) this;
		}

		public Criteria andTransTypeEqualTo(String value) {
			addCriterion("trans_type =", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotEqualTo(String value) {
			addCriterion("trans_type <>", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeGreaterThan(String value) {
			addCriterion("trans_type >", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeGreaterThanOrEqualTo(String value) {
			addCriterion("trans_type >=", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeLessThan(String value) {
			addCriterion("trans_type <", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeLessThanOrEqualTo(String value) {
			addCriterion("trans_type <=", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeLike(String value) {
			addCriterion("trans_type like", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotLike(String value) {
			addCriterion("trans_type not like", value, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeIn(List<String> values) {
			addCriterion("trans_type in", values, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotIn(List<String> values) {
			addCriterion("trans_type not in", values, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeBetween(String value1, String value2) {
			addCriterion("trans_type between", value1, value2, "transType");
			return (Criteria) this;
		}

		public Criteria andTransTypeNotBetween(String value1, String value2) {
			addCriterion("trans_type not between", value1, value2, "transType");
			return (Criteria) this;
		}

		public Criteria andGameTypeIsNull() {
			addCriterion("game_type is null");
			return (Criteria) this;
		}

		public Criteria andGameTypeIsNotNull() {
			addCriterion("game_type is not null");
			return (Criteria) this;
		}

		public Criteria andGameTypeEqualTo(String value) {
			addCriterion("game_type =", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeNotEqualTo(String value) {
			addCriterion("game_type <>", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeGreaterThan(String value) {
			addCriterion("game_type >", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeGreaterThanOrEqualTo(String value) {
			addCriterion("game_type >=", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeLessThan(String value) {
			addCriterion("game_type <", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeLessThanOrEqualTo(String value) {
			addCriterion("game_type <=", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeLike(String value) {
			addCriterion("game_type like", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeNotLike(String value) {
			addCriterion("game_type not like", value, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeIn(List<String> values) {
			addCriterion("game_type in", values, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeNotIn(List<String> values) {
			addCriterion("game_type not in", values, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeBetween(String value1, String value2) {
			addCriterion("game_type between", value1, value2, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameTypeNotBetween(String value1, String value2) {
			addCriterion("game_type not between", value1, value2, "gameType");
			return (Criteria) this;
		}

		public Criteria andGameIdIsNull() {
			addCriterion("game_id is null");
			return (Criteria) this;
		}

		public Criteria andGameIdIsNotNull() {
			addCriterion("game_id is not null");
			return (Criteria) this;
		}

		public Criteria andGameIdEqualTo(String value) {
			addCriterion("game_id =", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdNotEqualTo(String value) {
			addCriterion("game_id <>", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdGreaterThan(String value) {
			addCriterion("game_id >", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdGreaterThanOrEqualTo(String value) {
			addCriterion("game_id >=", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdLessThan(String value) {
			addCriterion("game_id <", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdLessThanOrEqualTo(String value) {
			addCriterion("game_id <=", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdLike(String value) {
			addCriterion("game_id like", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdNotLike(String value) {
			addCriterion("game_id not like", value, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdIn(List<String> values) {
			addCriterion("game_id in", values, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdNotIn(List<String> values) {
			addCriterion("game_id not in", values, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdBetween(String value1, String value2) {
			addCriterion("game_id between", value1, value2, "gameId");
			return (Criteria) this;
		}

		public Criteria andGameIdNotBetween(String value1, String value2) {
			addCriterion("game_id not between", value1, value2, "gameId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return (Criteria) this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return (Criteria) this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoIn(List<String> values) {
			addCriterion("memo in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotIn(List<String> values) {
			addCriterion("memo not in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ds_member_money_log
	 * @mbggenerated  Wed Oct 14 00:56:03 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ds_member_money_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 29 20:31:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}