package com.ds.money.entity;

public class DsMoneyConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.id
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.from_key
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private String fromKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.web_id
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private Integer webId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.web_name
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private String webName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.hashcode
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private String hashcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.iplist
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private String iplist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_money_config.state
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	private Short state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.id
	 * @return  the value of ds_money_config.id
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.id
	 * @param id  the value for ds_money_config.id
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.from_key
	 * @return  the value of ds_money_config.from_key
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public String getFromKey() {
		return fromKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.from_key
	 * @param fromKey  the value for ds_money_config.from_key
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setFromKey(String fromKey) {
		this.fromKey = fromKey == null ? null : fromKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.web_id
	 * @return  the value of ds_money_config.web_id
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public Integer getWebId() {
		return webId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.web_id
	 * @param webId  the value for ds_money_config.web_id
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setWebId(Integer webId) {
		this.webId = webId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.web_name
	 * @return  the value of ds_money_config.web_name
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public String getWebName() {
		return webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.web_name
	 * @param webName  the value for ds_money_config.web_name
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setWebName(String webName) {
		this.webName = webName == null ? null : webName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.hashcode
	 * @return  the value of ds_money_config.hashcode
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public String getHashcode() {
		return hashcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.hashcode
	 * @param hashcode  the value for ds_money_config.hashcode
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setHashcode(String hashcode) {
		this.hashcode = hashcode == null ? null : hashcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.iplist
	 * @return  the value of ds_money_config.iplist
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public String getIplist() {
		return iplist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.iplist
	 * @param iplist  the value for ds_money_config.iplist
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setIplist(String iplist) {
		this.iplist = iplist == null ? null : iplist.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_money_config.state
	 * @return  the value of ds_money_config.state
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public Short getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_money_config.state
	 * @param state  the value for ds_money_config.state
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setState(Short state) {
		this.state = state;
	}
}