package com.ds.money.entity;

import java.util.ArrayList;
import java.util.List;

public class DsMoneyConfigExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public DsMoneyConfigExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFromKeyIsNull() {
			addCriterion("from_key is null");
			return (Criteria) this;
		}

		public Criteria andFromKeyIsNotNull() {
			addCriterion("from_key is not null");
			return (Criteria) this;
		}

		public Criteria andFromKeyEqualTo(String value) {
			addCriterion("from_key =", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotEqualTo(String value) {
			addCriterion("from_key <>", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyGreaterThan(String value) {
			addCriterion("from_key >", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyGreaterThanOrEqualTo(String value) {
			addCriterion("from_key >=", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyLessThan(String value) {
			addCriterion("from_key <", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyLessThanOrEqualTo(String value) {
			addCriterion("from_key <=", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyLike(String value) {
			addCriterion("from_key like", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotLike(String value) {
			addCriterion("from_key not like", value, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyIn(List<String> values) {
			addCriterion("from_key in", values, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotIn(List<String> values) {
			addCriterion("from_key not in", values, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyBetween(String value1, String value2) {
			addCriterion("from_key between", value1, value2, "fromKey");
			return (Criteria) this;
		}

		public Criteria andFromKeyNotBetween(String value1, String value2) {
			addCriterion("from_key not between", value1, value2, "fromKey");
			return (Criteria) this;
		}

		public Criteria andWebIdIsNull() {
			addCriterion("web_id is null");
			return (Criteria) this;
		}

		public Criteria andWebIdIsNotNull() {
			addCriterion("web_id is not null");
			return (Criteria) this;
		}

		public Criteria andWebIdEqualTo(Integer value) {
			addCriterion("web_id =", value, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdNotEqualTo(Integer value) {
			addCriterion("web_id <>", value, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdGreaterThan(Integer value) {
			addCriterion("web_id >", value, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("web_id >=", value, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdLessThan(Integer value) {
			addCriterion("web_id <", value, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdLessThanOrEqualTo(Integer value) {
			addCriterion("web_id <=", value, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdIn(List<Integer> values) {
			addCriterion("web_id in", values, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdNotIn(List<Integer> values) {
			addCriterion("web_id not in", values, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdBetween(Integer value1, Integer value2) {
			addCriterion("web_id between", value1, value2, "webId");
			return (Criteria) this;
		}

		public Criteria andWebIdNotBetween(Integer value1, Integer value2) {
			addCriterion("web_id not between", value1, value2, "webId");
			return (Criteria) this;
		}

		public Criteria andWebNameIsNull() {
			addCriterion("web_name is null");
			return (Criteria) this;
		}

		public Criteria andWebNameIsNotNull() {
			addCriterion("web_name is not null");
			return (Criteria) this;
		}

		public Criteria andWebNameEqualTo(String value) {
			addCriterion("web_name =", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotEqualTo(String value) {
			addCriterion("web_name <>", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameGreaterThan(String value) {
			addCriterion("web_name >", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameGreaterThanOrEqualTo(String value) {
			addCriterion("web_name >=", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameLessThan(String value) {
			addCriterion("web_name <", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameLessThanOrEqualTo(String value) {
			addCriterion("web_name <=", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameLike(String value) {
			addCriterion("web_name like", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotLike(String value) {
			addCriterion("web_name not like", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameIn(List<String> values) {
			addCriterion("web_name in", values, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotIn(List<String> values) {
			addCriterion("web_name not in", values, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameBetween(String value1, String value2) {
			addCriterion("web_name between", value1, value2, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotBetween(String value1, String value2) {
			addCriterion("web_name not between", value1, value2, "webName");
			return (Criteria) this;
		}

		public Criteria andHashcodeIsNull() {
			addCriterion("hashcode is null");
			return (Criteria) this;
		}

		public Criteria andHashcodeIsNotNull() {
			addCriterion("hashcode is not null");
			return (Criteria) this;
		}

		public Criteria andHashcodeEqualTo(String value) {
			addCriterion("hashcode =", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotEqualTo(String value) {
			addCriterion("hashcode <>", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeGreaterThan(String value) {
			addCriterion("hashcode >", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeGreaterThanOrEqualTo(String value) {
			addCriterion("hashcode >=", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeLessThan(String value) {
			addCriterion("hashcode <", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeLessThanOrEqualTo(String value) {
			addCriterion("hashcode <=", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeLike(String value) {
			addCriterion("hashcode like", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotLike(String value) {
			addCriterion("hashcode not like", value, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeIn(List<String> values) {
			addCriterion("hashcode in", values, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotIn(List<String> values) {
			addCriterion("hashcode not in", values, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeBetween(String value1, String value2) {
			addCriterion("hashcode between", value1, value2, "hashcode");
			return (Criteria) this;
		}

		public Criteria andHashcodeNotBetween(String value1, String value2) {
			addCriterion("hashcode not between", value1, value2, "hashcode");
			return (Criteria) this;
		}

		public Criteria andIplistIsNull() {
			addCriterion("iplist is null");
			return (Criteria) this;
		}

		public Criteria andIplistIsNotNull() {
			addCriterion("iplist is not null");
			return (Criteria) this;
		}

		public Criteria andIplistEqualTo(String value) {
			addCriterion("iplist =", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistNotEqualTo(String value) {
			addCriterion("iplist <>", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistGreaterThan(String value) {
			addCriterion("iplist >", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistGreaterThanOrEqualTo(String value) {
			addCriterion("iplist >=", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistLessThan(String value) {
			addCriterion("iplist <", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistLessThanOrEqualTo(String value) {
			addCriterion("iplist <=", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistLike(String value) {
			addCriterion("iplist like", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistNotLike(String value) {
			addCriterion("iplist not like", value, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistIn(List<String> values) {
			addCriterion("iplist in", values, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistNotIn(List<String> values) {
			addCriterion("iplist not in", values, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistBetween(String value1, String value2) {
			addCriterion("iplist between", value1, value2, "iplist");
			return (Criteria) this;
		}

		public Criteria andIplistNotBetween(String value1, String value2) {
			addCriterion("iplist not between", value1, value2, "iplist");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Short value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Short value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Short value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Short value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Short value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Short value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Short> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Short> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Short value1, Short value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Short value1, Short value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ds_money_config
	 * @mbggenerated  Thu Jun 04 13:54:16 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ds_money_config
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 04 13:36:06 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}