package com.ds.money.entity;

public class DsSiteHashcode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_site_hashcode.site_id
	 * @mbggenerated  Thu Jun 04 13:50:38 CST 2015
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_site_hashcode.hashcode
	 * @mbggenerated  Thu Jun 04 13:50:38 CST 2015
	 */
	private String hashcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_site_hashcode.site_id
	 * @return  the value of ds_site_hashcode.site_id
	 * @mbggenerated  Thu Jun 04 13:50:38 CST 2015
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_site_hashcode.site_id
	 * @param siteId  the value for ds_site_hashcode.site_id
	 * @mbggenerated  Thu Jun 04 13:50:38 CST 2015
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_site_hashcode.hashcode
	 * @return  the value of ds_site_hashcode.hashcode
	 * @mbggenerated  Thu Jun 04 13:50:38 CST 2015
	 */
	public String getHashcode() {
		return hashcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_site_hashcode.hashcode
	 * @param hashcode  the value for ds_site_hashcode.hashcode
	 * @mbggenerated  Thu Jun 04 13:50:38 CST 2015
	 */
	public void setHashcode(String hashcode) {
		this.hashcode = hashcode == null ? null : hashcode.trim();
	}
}