package com.ds.money.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MemberEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public MemberEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("site_id is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("site_id is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(Integer value) {
            addCriterion("site_id =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(Integer value) {
            addCriterion("site_id <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(Integer value) {
            addCriterion("site_id >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("site_id >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(Integer value) {
            addCriterion("site_id <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("site_id <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<Integer> values) {
            addCriterion("site_id in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<Integer> values) {
            addCriterion("site_id not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(Integer value1, Integer value2) {
            addCriterion("site_id between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("site_id not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteNameIsNull() {
            addCriterion("site_name is null");
            return (Criteria) this;
        }

        public Criteria andSiteNameIsNotNull() {
            addCriterion("site_name is not null");
            return (Criteria) this;
        }

        public Criteria andSiteNameEqualTo(String value) {
            addCriterion("site_name =", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotEqualTo(String value) {
            addCriterion("site_name <>", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameGreaterThan(String value) {
            addCriterion("site_name >", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
            addCriterion("site_name >=", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLessThan(String value) {
            addCriterion("site_name <", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLessThanOrEqualTo(String value) {
            addCriterion("site_name <=", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLike(String value) {
            addCriterion("site_name like", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotLike(String value) {
            addCriterion("site_name not like", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameIn(List<String> values) {
            addCriterion("site_name in", values, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotIn(List<String> values) {
            addCriterion("site_name not in", values, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameBetween(String value1, String value2) {
            addCriterion("site_name between", value1, value2, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotBetween(String value1, String value2) {
            addCriterion("site_name not between", value1, value2, "siteName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andAgentsIsNull() {
            addCriterion("agents is null");
            return (Criteria) this;
        }

        public Criteria andAgentsIsNotNull() {
            addCriterion("agents is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsEqualTo(String value) {
            addCriterion("agents =", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsNotEqualTo(String value) {
            addCriterion("agents <>", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsGreaterThan(String value) {
            addCriterion("agents >", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsGreaterThanOrEqualTo(String value) {
            addCriterion("agents >=", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsLessThan(String value) {
            addCriterion("agents <", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsLessThanOrEqualTo(String value) {
            addCriterion("agents <=", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsLike(String value) {
            addCriterion("agents like", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsNotLike(String value) {
            addCriterion("agents not like", value, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsIn(List<String> values) {
            addCriterion("agents in", values, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsNotIn(List<String> values) {
            addCriterion("agents not in", values, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsBetween(String value1, String value2) {
            addCriterion("agents between", value1, value2, "agents");
            return (Criteria) this;
        }

        public Criteria andAgentsNotBetween(String value1, String value2) {
            addCriterion("agents not between", value1, value2, "agents");
            return (Criteria) this;
        }

        public Criteria andWorldIsNull() {
            addCriterion("world is null");
            return (Criteria) this;
        }

        public Criteria andWorldIsNotNull() {
            addCriterion("world is not null");
            return (Criteria) this;
        }

        public Criteria andWorldEqualTo(String value) {
            addCriterion("world =", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldNotEqualTo(String value) {
            addCriterion("world <>", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldGreaterThan(String value) {
            addCriterion("world >", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldGreaterThanOrEqualTo(String value) {
            addCriterion("world >=", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldLessThan(String value) {
            addCriterion("world <", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldLessThanOrEqualTo(String value) {
            addCriterion("world <=", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldLike(String value) {
            addCriterion("world like", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldNotLike(String value) {
            addCriterion("world not like", value, "world");
            return (Criteria) this;
        }

        public Criteria andWorldIn(List<String> values) {
            addCriterion("world in", values, "world");
            return (Criteria) this;
        }

        public Criteria andWorldNotIn(List<String> values) {
            addCriterion("world not in", values, "world");
            return (Criteria) this;
        }

        public Criteria andWorldBetween(String value1, String value2) {
            addCriterion("world between", value1, value2, "world");
            return (Criteria) this;
        }

        public Criteria andWorldNotBetween(String value1, String value2) {
            addCriterion("world not between", value1, value2, "world");
            return (Criteria) this;
        }

        public Criteria andCorpratorIsNull() {
            addCriterion("corprator is null");
            return (Criteria) this;
        }

        public Criteria andCorpratorIsNotNull() {
            addCriterion("corprator is not null");
            return (Criteria) this;
        }

        public Criteria andCorpratorEqualTo(String value) {
            addCriterion("corprator =", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorNotEqualTo(String value) {
            addCriterion("corprator <>", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorGreaterThan(String value) {
            addCriterion("corprator >", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorGreaterThanOrEqualTo(String value) {
            addCriterion("corprator >=", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorLessThan(String value) {
            addCriterion("corprator <", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorLessThanOrEqualTo(String value) {
            addCriterion("corprator <=", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorLike(String value) {
            addCriterion("corprator like", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorNotLike(String value) {
            addCriterion("corprator not like", value, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorIn(List<String> values) {
            addCriterion("corprator in", values, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorNotIn(List<String> values) {
            addCriterion("corprator not in", values, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorBetween(String value1, String value2) {
            addCriterion("corprator between", value1, value2, "corprator");
            return (Criteria) this;
        }

        public Criteria andCorpratorNotBetween(String value1, String value2) {
            addCriterion("corprator not between", value1, value2, "corprator");
            return (Criteria) this;
        }

        public Criteria andSuperiorIsNull() {
            addCriterion("superior is null");
            return (Criteria) this;
        }

        public Criteria andSuperiorIsNotNull() {
            addCriterion("superior is not null");
            return (Criteria) this;
        }

        public Criteria andSuperiorEqualTo(String value) {
            addCriterion("superior =", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotEqualTo(String value) {
            addCriterion("superior <>", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorGreaterThan(String value) {
            addCriterion("superior >", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorGreaterThanOrEqualTo(String value) {
            addCriterion("superior >=", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorLessThan(String value) {
            addCriterion("superior <", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorLessThanOrEqualTo(String value) {
            addCriterion("superior <=", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorLike(String value) {
            addCriterion("superior like", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotLike(String value) {
            addCriterion("superior not like", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorIn(List<String> values) {
            addCriterion("superior in", values, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotIn(List<String> values) {
            addCriterion("superior not in", values, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorBetween(String value1, String value2) {
            addCriterion("superior between", value1, value2, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotBetween(String value1, String value2) {
            addCriterion("superior not between", value1, value2, "superior");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("company like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("company not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCommAgentIsNull() {
            addCriterion("comm_agent is null");
            return (Criteria) this;
        }

        public Criteria andCommAgentIsNotNull() {
            addCriterion("comm_agent is not null");
            return (Criteria) this;
        }

        public Criteria andCommAgentEqualTo(BigDecimal value) {
            addCriterion("comm_agent =", value, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentNotEqualTo(BigDecimal value) {
            addCriterion("comm_agent <>", value, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentGreaterThan(BigDecimal value) {
            addCriterion("comm_agent >", value, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_agent >=", value, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentLessThan(BigDecimal value) {
            addCriterion("comm_agent <", value, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_agent <=", value, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentIn(List<BigDecimal> values) {
            addCriterion("comm_agent in", values, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentNotIn(List<BigDecimal> values) {
            addCriterion("comm_agent not in", values, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_agent between", value1, value2, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommAgentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_agent not between", value1, value2, "commAgent");
            return (Criteria) this;
        }

        public Criteria andCommWorldIsNull() {
            addCriterion("comm_world is null");
            return (Criteria) this;
        }

        public Criteria andCommWorldIsNotNull() {
            addCriterion("comm_world is not null");
            return (Criteria) this;
        }

        public Criteria andCommWorldEqualTo(BigDecimal value) {
            addCriterion("comm_world =", value, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldNotEqualTo(BigDecimal value) {
            addCriterion("comm_world <>", value, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldGreaterThan(BigDecimal value) {
            addCriterion("comm_world >", value, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_world >=", value, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldLessThan(BigDecimal value) {
            addCriterion("comm_world <", value, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldLessThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_world <=", value, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldIn(List<BigDecimal> values) {
            addCriterion("comm_world in", values, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldNotIn(List<BigDecimal> values) {
            addCriterion("comm_world not in", values, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_world between", value1, value2, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommWorldNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_world not between", value1, value2, "commWorld");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorIsNull() {
            addCriterion("comm_corprator is null");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorIsNotNull() {
            addCriterion("comm_corprator is not null");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorEqualTo(BigDecimal value) {
            addCriterion("comm_corprator =", value, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorNotEqualTo(BigDecimal value) {
            addCriterion("comm_corprator <>", value, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorGreaterThan(BigDecimal value) {
            addCriterion("comm_corprator >", value, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_corprator >=", value, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorLessThan(BigDecimal value) {
            addCriterion("comm_corprator <", value, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorLessThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_corprator <=", value, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorIn(List<BigDecimal> values) {
            addCriterion("comm_corprator in", values, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorNotIn(List<BigDecimal> values) {
            addCriterion("comm_corprator not in", values, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_corprator between", value1, value2, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommCorpratorNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_corprator not between", value1, value2, "commCorprator");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorIsNull() {
            addCriterion("comm_superior is null");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorIsNotNull() {
            addCriterion("comm_superior is not null");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorEqualTo(BigDecimal value) {
            addCriterion("comm_superior =", value, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorNotEqualTo(BigDecimal value) {
            addCriterion("comm_superior <>", value, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorGreaterThan(BigDecimal value) {
            addCriterion("comm_superior >", value, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_superior >=", value, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorLessThan(BigDecimal value) {
            addCriterion("comm_superior <", value, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorLessThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_superior <=", value, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorIn(List<BigDecimal> values) {
            addCriterion("comm_superior in", values, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorNotIn(List<BigDecimal> values) {
            addCriterion("comm_superior not in", values, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_superior between", value1, value2, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommSuperiorNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_superior not between", value1, value2, "commSuperior");
            return (Criteria) this;
        }

        public Criteria andCommBranchIsNull() {
            addCriterion("comm_branch is null");
            return (Criteria) this;
        }

        public Criteria andCommBranchIsNotNull() {
            addCriterion("comm_branch is not null");
            return (Criteria) this;
        }

        public Criteria andCommBranchEqualTo(BigDecimal value) {
            addCriterion("comm_branch =", value, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchNotEqualTo(BigDecimal value) {
            addCriterion("comm_branch <>", value, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchGreaterThan(BigDecimal value) {
            addCriterion("comm_branch >", value, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_branch >=", value, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchLessThan(BigDecimal value) {
            addCriterion("comm_branch <", value, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchLessThanOrEqualTo(BigDecimal value) {
            addCriterion("comm_branch <=", value, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchIn(List<BigDecimal> values) {
            addCriterion("comm_branch in", values, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchNotIn(List<BigDecimal> values) {
            addCriterion("comm_branch not in", values, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_branch between", value1, value2, "commBranch");
            return (Criteria) this;
        }

        public Criteria andCommBranchNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("comm_branch not between", value1, value2, "commBranch");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ds_member
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 06 03:05:53 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ds_member
     *
     * @mbggenerated Thu Aug 06 03:05:53 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}