server:
  port: 8072

mybatis.mapper-locations: classpath:com/ds/**/*.xml

spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://192.168.1.230:3306/openapi
    username: root
    password: eason
    connectionProperties: config.decrypt=false
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: config,stat
    maxWait: 60000
    maxActive: 20
    initialSize: 1
    minIdle: 1
    validationQuery: select 1
    testWhileIdle: true
    poolPreparedStatements: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true

# spring.data.mongodb.uri:  mongodb://eason:eason@10.10.4.230:27017/lottery

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database:  0
spring.redis.database10:  10
# Redis服务器地址
spring.redis.host:  192.168.1.230
# Redis服务器连接端口
spring.redis.port:  6379
# Redis服务器连接密码（默认为空）
spring.redis.password:
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: -1
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 0
#TestOnBorrow设置为false，导致有时获取的连接不可用
spring.redis.testOnBorrow:  false
