package com.eason.report.pull.h8.mapper;

import com.eason.report.pull.h8.entity.M8SportEntityExample;
import com.eason.report.pull.h8.vo.fetchRo;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface M8SportEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int countByExample(M8SportEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int deleteByExample(M8SportEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int insert(fetchRo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int insertSelective(fetchRo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	List<fetchRo> selectByExample(M8SportEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	fetchRo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int updateByExampleSelective(@Param("record") fetchRo record,
                                 @Param("example") M8SportEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int updateByExample(@Param("record") fetchRo record,
                        @Param("example") M8SportEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int updateByPrimaryKeySelective(fetchRo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	int updateByPrimaryKey(fetchRo record);
}