package com.eason.report.pull.h8.mapper;

import com.ds.temp.entity.AuditTotalVO;
import com.ds.temp.entity.DsAuditTotal;
import com.ds.temp.entity.TempAuditTotal;
import com.ds.temp.entity.TempAuditTotalExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TempAuditTotalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int countByExample(TempAuditTotalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int deleteByExample(TempAuditTotalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int insert(TempAuditTotal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int insertSelective(TempAuditTotal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	List<TempAuditTotal> selectByExample(TempAuditTotalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	TempAuditTotal selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TempAuditTotal record, @Param("example") TempAuditTotalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int updateByExample(@Param("record") TempAuditTotal record, @Param("example") TempAuditTotalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int updateByPrimaryKeySelective(TempAuditTotal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temp_audit_total
	 * @mbggenerated  Wed Oct 07 22:52:53 CST 2015
	 */
	int updateByPrimaryKey(TempAuditTotal record);
	void updateByOrderNo(TempAuditTotal record);
	DsAuditTotal auditByExample(TempAuditTotalExample example);
	
	void insertOrupdate(@Param("item") AuditTotalVO record, @Param("siteId") Integer siteId);
	void batInsertOrupdate(@Param("list") List<AuditTotalVO> recordList, @Param("siteId") Integer siteId);

	//稽核统计--audit_total_siteId
	DsAuditTotal getAuditTotalBySiteIdAndUser(@Param("siteId") Integer siteId, @Param("userName") String userName,
                                              @Param("start_time") String start_time, @Param("end_time") String end_time);
}